### ISSUE TITLE
Add a link to this github repository for editing.

### ISSUE THREAD

**Issue by ngbrown** [openpilot-community/documentation#6]
As far as I could tell, there wasn't an actual link back to this repository.  The github link in the top right corner is to https://github.com/commaai/openpilot.

There is nothing on the contributing page on what git repository to clone.

**Comment by jfrux** [comment]
Sorry Nathan… this world is moving much faster than me and unfortunately I have pivoted the project a bit due to limited time and support so its now beginning to take the form of database.opc.ai.
I will be removing these repos and the other docs site today to prevent further confusion.

They will redirect to the database project so we can actually build interaction logic into it.
You can help contribute code to https://github.com/openpilot-community/openpilotdb if you’re interested!

Or, if you want to contribute data, I will be working to get the functionality needed to make it more useful to the community so please fill out an issue at that link as well if you want features or a specific view of something.

I have a lot of data in the background that you can’t currently see so check with me if you need some data that isn’t exposed.

Thanks again for your willingness to search this out.
